package edu.hawaii.photohunt.webapp.model;

/**
 * A PictureFileException is thrown when there is an error while accessing a file in the Model
 * classes.
 * 
 * @author George Lee
 * 
 */
public class PictureFileException extends Exception {

  /**
   * Serial version UID, automatically generated by Eclipse.
   */
  private static final long serialVersionUID = -4897351898577391966L;

  /**
   * Indicates that a model attempted to open an invalid file.
   * 
   * @param message An error message describing the cause of the problem.
   */

  public PictureFileException(String message) {
    super(message);
  }

  /**
   * Indicates that a model attempted to open an invalid file.
   * 
   * @param e The exception that was the root cause of this exception.
   */
  public PictureFileException(Exception e) {
    super(e);
  }

  /**
   * Indicates that a model attempted to open an invalid file.
   * 
   * @param e The exception that was the root cause of this exception.
   * @param message An error message describing the cause of the problem.
   */
  public PictureFileException(Exception e, String message) {
    super(e);
  }
}