# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "pictures", :force => true do |t|
    t.column "user_email",   :string
    t.column "tag",          :string
    t.column "description",  :string
    t.column "date",         :date
    t.column "score",        :integer
    t.column "content_type", :string
    t.column "data",         :binary
    t.column "status",       :string
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "tags", :force => true do |t|
    t.column "short_description", :string
    t.column "long_description",  :string
  end

  create_table "users", :force => true do |t|
    t.column "name",            :string
    t.column "email",           :string
    t.column "hashed_password", :string
    t.column "salt",            :string
  end

end
